// This file is generated by GoAdmin CLI adm.
package tables

import "github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"

// Generators is a map of table models.
//
// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "app_urlgroup" => http://localhost:9033/admin/info/app_urlgroup
// "app_urlinfor" => http://localhost:9033/admin/info/app_urlinfor
//
// example end
var Generators = map[string]table.Generator{
	"group": GetAppUrlgroupTable,
	"url":   GetAppUrlinforTable,

	// generators end
}
